server:
  servlet.context-path: /finapp-card-service-qa

build:
  version: 1.0

cards:
  env-name: Quality Assurance Environment
  service-name: finapp-card-service-qa
  developers:
    - "Han"
    - "Duy"
    - "Quan"
  schemas:
    card: 1.0-qa
