server:
  servlet.context-path: /finapp-card-service

build:
  version: 1.0

accounts:
  service-name: finapp-card-service
  developers:
    - "Han"
    - "Duy"
    - "Quan"
  schemas:
    account: 1.0
    customer: 1.0