spring:
  application:
    name: cards

server:
  port: 8089
  servlet.context-path: "/finapp-card-service/dev"

build:
  version: 1.0

cards:
  service-name: finapp-card-service-dev
  developers:
    - "Han"
    - "Duy"
    - "Quan"
  schemas:
    card: 1.0-dev
