server:
  servlet.context-path: /finapp-card-service-qa

build:
  version: 1.1

cards:
  service-name: finapp-card-service-qa
  developers:
    - "Han"
    - "Duy"
    - "Quan"
  schemas:
    card: 1.0-qa
