server:
  servlet.context-path: /finapp-card-service-qa

build:
  version: 1.0

cards:
  service-name: finapp-card-service-qa
  developers:
    - "Han-qa"
    - "Duy-qa"
    - "Quan-qa"
  schemas:
    card: 1.0-qa
