server:
  port: 8761

spring:
  application:
    name: service-discovery
  config:
    import: "optional:configserver:http://localhost:8071/application"

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true

