spring:
  application:
    name: loans

server:
  port: 8090

build:
  version: 1.0

loans:
  service-name: finapp-loan-service-dev
  env-name: Developer (dev)
  developers:
    - "Han"
    - "Duy"
    - "Quan"
  schemas:
    loan: 1.0-dev