server:
  servlet.context-path: /finapp-loan-service-qa

build:
  version: 1.0

accounts:
  service-name: finapp-loan-service-qa
  developers:
    - "Han"
    - "Duy"
    - "Quan"
  schemas:
    account: 1.0-qa
    customer: 1.0-qa