spring:
  application:
    name: loans
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true

server:
  port: 8090

build:
  version: 1.0

eureka:
  instance:
    hostname: localhost
    statusPageUrlPath: /api/v1/build/info
    healthCheckUrlPath: /actuator/health
    healthcheck:
      enabled: true
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - busrefresh
          - health
          - shutdown
  endpoint:
    refresh:
      enabled: true
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env.enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

endpoints:
  shutdown:
    enabled: true

springdoc:
  show-actuator: true

loans:
  service-name: finapp-loan-service-dev
  env-name: Developer (dev)
  developers:
    - "Han"
    - "Duy"
    - "Quan"
  schemas:
    loan: 1.0-dev