server:
  servlet.context-path: /finapp-loan-service-qa

build:
  version: 1.0

loans:
  service-name: finapp-loan-service-qa
  developers:
    - "Han-qa"
    - "Duy-qa"
    - "Quan-qa"
  schemas:
    loan: 1.0-qa