version: "3"

services:

  rabbit:
    image: rabbitmq:3.12-management
    container_name: "finapp-rabbit"
    ports:
      - "5672:5672"
      - "15672:15672"
    extends:
      file: common.yml
      service: network-service
    healthcheck:
      test: "rabbitmq-diagnostics check_port_connectivity"

  config-central:
    image: "finapp/configuration-central:1.0.0"
    container_name: "finapp-config-central"
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    extends:
      file: common.yml
      service: base-config-service
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"

  accounts:
    image: "finapp/accounts:1.0.0"
    container_name: "finapp-account-service"
    ports:
      - "8088:8088"
    extends:
      file: "common.yml"
      service: base-application-service
    healthcheck:
      test: "curl --fail --silent localhost:8088/actuator/health/readiness | grep UP || exit 1"
    environment:
      SPRING_APPLICATION_NAME: accounts

  cards:
    image: "finapp/cards:1.0.0"
    container_name: "finapp-card-service"
    ports:
      - "8089:8089"
    extends:
      file: "common.yml"
      service: base-application-service
    healthcheck:
      test: "curl --fail --silent localhost:8089/actuator/health/readiness | grep UP || exit 1"
    environment:
      SPRING_APPLICATION_NAME: cards

  loans:
    image: "finapp/loans:1.0.0"
    container_name: "finapp-loan-service"
    ports:
      - "8090:8090"
    extends:
      file: "common.yml"
      service: base-application-service
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
    environment:
      SPRING_APPLICATION_NAME: loans

networks:
  finapp:
    driver: bridge