version: "3"

services:

  rabbit:
    image: rabbitmq:3.12-management
    container_name: "finapp-rabbit"
    ports:
      - "5672:5672"
      - "15672:15672"
    extends:
      file: common.yml
      service: network-service
    healthcheck:
      test: "rabbitmq-diagnostics check_port_connectivity"

  config-central:
    image: "finapp/configuration-central:1.0.0"
    container_name: "finapp-config-central"
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    extends:
      file: common.yml
      service: base-config-service
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
    environment:
      SPRING_APPLICATION_NAME: config-central

  service-discovery:
    image: "finapp/service-discovery:1.0.0"
    container_name: "finapp-service-discovery"
    ports:
      - "8761:8761"
    extends:
      file: common.yml
      service: base-config-service
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 1"
    environment:
      SPRING_APPLICATION_NAME: service-discovery
      SPRING_CONFIG_IMPORT: "configserver:http://config-central:8071/application"
    depends_on:
      config-central:
        condition: service_healthy

  accounts:
    image: "finapp/accounts:1.0.0"
    container_name: "finapp-account-service"
    ports:
      - "8088:8088"
    extends:
      file: "common.yml"
      service: base-application-service
    healthcheck:
      test: "curl --fail --silent localhost:8088/actuator/health/readiness | grep UP || exit 1"
    environment:
      SPRING_APPLICATION_NAME: accounts
      SPRING_DATASOURCE_URL: jdbc:postgresql://finapp-account-db:5432/account-db

  cards:
    image: "finapp/cards:1.0.0"
    container_name: "finapp-card-service"
    ports:
      - "8089:8089"
    extends:
      file: "common.yml"
      service: base-application-service
    healthcheck:
      test: "curl --fail --silent localhost:8089/actuator/health/readiness | grep UP || exit 1"
    environment:
      SPRING_APPLICATION_NAME: cards
      SPRING_DATASOURCE_URL: jdbc:postgresql://finapp-card-db:5432/card-db

  loans:
    image: "finapp/loans:1.0.0"
    container_name: "finapp-loan-service"
    ports:
      - "8090:8090"
    extends:
      file: "common.yml"
      service: base-application-service
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
    environment:
      SPRING_APPLICATION_NAME: loans
      SPRING_DATASOURCE_URL: jdbc:postgresql://finapp-loan-db:5432/loan-db

networks:
  finapp:
    driver: bridge