server:
  port: 8071

springdoc:
  show-actuator: true

spring:
  application:
    name: "finapp-configuration-central"

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  profiles:
    active:
      - "native"
      - "git"

  cloud:
    config:
      server:
        prefix: "application"
        git:
          uri: "https://github.com/handonn2000/ms-finapp-demo.git"
          default-label: master
          timeout: 10
          force-pull: true
          search-paths:
            - "configurations/src/main/resources/configs"
            - "configurations/src/main/resources/configs/accounts"
            - "configurations/src/main/resources/configs/cards"
            - "configurations/src/main/resources/configs/loans"
        native:
          search-locations:
            - "classpath:/configs"
            - "classpath:/configs/accounts"
            - "classpath:/configs/cards"
            - "classpath:/configs/loans"

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - busrefresh
          - health
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

eureka:
  instance:
    hostname: localhost
    healthCheckUrlPath: /actuator/health
    healthcheck:
      enabled: true
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/