spring:
  application:
    name: "finapp-configuration-central"
  profiles:
    active:
      - "native"
  cloud:
    config:
      server:
        native:
          search-locations:
            - "classpath:/configs/accounts"
            - "classpath:/configs/cards"
            - "classpath:/configs/loans"

server:
  port: 8071
  servlet:
    context-path: "/finapp-configuration-central"
