server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - busrefresh
          - health
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    refresh:
      enabled: true
    health:
      probes:
        enabled: true