server:
  servlet.context-path: /finapp-account-service-qa

build:
  version: 1.1

accounts:
  service-name: finapp-account-service-qa
  developers:
    - "Han"
    - "Duy"
    - "Quan"
  schemas:
    account: 1.0-QA
    customer: 1.0-QA
