spring:
  application:
    name: accounts

server:
  port: 8088
  servlet.context-path: "/finapp-account-service/dev"

build:
  version: 1.0

accounts:
  service-name: finapp-account-service-dev
  developers:
    - "Han"
    - "Duy"
    - "Quan"
  schemas:
    account: 1.0-dev
    customer: 1.0-dev