server:
  servlet.context-path: /finapp-account-service-qa

build:
  version: 1.0

accounts:
  env-name: Quality Assurance Environment
  service-name: finapp-account-service-qa
  developers:
    - "Han"
    - "Duy"
    - "Quan"
  schemas:
    account: 1.0-QA
    customer: 1.0-QA
