build:
  version: 1.0

accounts:
  service-name: finapp-account-service-qa
  env-name: Quality Assurance
  developers:
    - "Han"
    - "Duy"
    - "Quan"
  schemas:
    account: 1.0-QA
    customer: 1.0-QA
